version: '3.8'

services:
  strava-mcp:
    image: ghcr.io/emiliermottet/strava-mcp:latest
    container_name: strava-mcp-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Optional: Export path for GPX/TCX files
      - ROUTE_EXPORT_PATH=/app/exports
      # Enable HTTP/SSE mode for metaMCP integration
      - USE_HTTP=true
      - PORT=3000
    volumes:
      # Mount a volume for route exports (optional)
      - ./strava-exports:/app/exports
      # Mount .env file for persistent token storage
      - ./.env:/app/.env
    # Port 3000 is only accessible within the Docker network (not exposed to localhost)
    # Uncomment the following line only if you need to test locally outside Docker
    # ports:
    #   - "3000:3000"
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

# If you're using this with metaMCP, you might want to add networking
networks:
  default:
    name: metamcp-network
    external: true
